jobs

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -12,54 +12,55 @@ inputs:
     required: false
     default: '3.9'
 
-runs:
-  using: "composite"
-  steps: 
-    - uses: actions/checkout@v3
-        with:
-          ref: 'main'
-    - uses: actions/setup-python@v3
-      with:
-        python-version: ${{ inputs.version }}
-        cache: "pip"
-        cache-dependency-path: settings.ini
-    - name: Test with nbdev
-      env:
-        USE_PRE: ${{ inputs.pre }}
-      shell: bash
-      run: |
-        set -ux
-        python -m pip install --upgrade pip
-        if [ $USE_PRE ]; then
-          pip install -U git+https://github.com/fastai/fastcore.git
-          pip install -U git+https://github.com/fastai/ghapi.git
-          pip install -U git+https://github.com/fastai/execnb.git
-          pip install -U git+https://github.com/fastai/nbdev.git
-        else
-          pip install -U nbdev
-        fi
-        echo "Doing editable install..."
-        test -f setup.py && pip install -e ".[dev]"
-        echo "Check we are starting with clean git checkout"
-        if [[ `git status --porcelain -uno` ]]; then
-          git diff
-          echo "git status is not clean"
-          false
-        fi
-        echo "Trying to strip out notebooks"
-        nbdev_clean
-        echo "Check that strip out was unnecessary"
-        git status -s # display the status to see which nbs need cleaning up
-        if [[ `git status --porcelain -uno` ]]; then
-          git status -uno
-          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
-          false
-        fi
-        nbdev_export
-        if [[ `git status --porcelain -uno` ]]; then
-          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
-          git status -uno
-          git diff
-          exit 1;
-        fi
-        nbdev_test
+jobs:
+    runs:
+      using: "composite"
+      steps: 
+        - uses: actions/checkout@v3
+            with:
+              ref: 'main'
+        - uses: actions/setup-python@v3
+          with:
+            python-version: ${{ inputs.version }}
+            cache: "pip"
+            cache-dependency-path: settings.ini
+        - name: Test with nbdev
+          env:
+            USE_PRE: ${{ inputs.pre }}
+          shell: bash
+          run: |
+            set -ux
+            python -m pip install --upgrade pip
+            if [ $USE_PRE ]; then
+              pip install -U git+https://github.com/fastai/fastcore.git
+              pip install -U git+https://github.com/fastai/ghapi.git
+              pip install -U git+https://github.com/fastai/execnb.git
+              pip install -U git+https://github.com/fastai/nbdev.git
+            else
+              pip install -U nbdev
+            fi
+            echo "Doing editable install..."
+            test -f setup.py && pip install -e ".[dev]"
+            echo "Check we are starting with clean git checkout"
+            if [[ `git status --porcelain -uno` ]]; then
+              git diff
+              echo "git status is not clean"
+              false
+            fi
+            echo "Trying to strip out notebooks"
+            nbdev_clean
+            echo "Check that strip out was unnecessary"
+            git status -s # display the status to see which nbs need cleaning up
+            if [[ `git status --porcelain -uno` ]]; then
+              git status -uno
+              echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+              false
+            fi
+            nbdev_export
+            if [[ `git status --porcelain -uno` ]]; then
+              echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+              git status -uno
+              git diff
+              exit 1;
+            fi
+            nbdev_test
